# Generated by Django 4.1.7 on 2023-04-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
            ],
        ),
    ]
