# Generated by Django 4.1.7 on 2023-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
