# Generated by Django 4.1.7 on 2023-04-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_owner', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('room_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('hotel_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_owner.hotelowner')),
            ],
        ),
    ]
