# Generated by Django 4.1.7 on 2023-05-09 22:00

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to=hotel.models.name_file),
        ),
    ]
